version: 0.0
os: linux
files:  
  - source: /    
    destination: /var/www/html/

hooks:  
  BeforeInstall:    
    - location: scripts/before-install.sh 
      runas: ubuntu 

  AfterInstall:    
    - location: scripts/after-install.sh
      runas: ubuntu

file_exists_behavior: OVERWRITE